env: dev
fluent-bit:
  daemonset:
    enabled: true
  pdb:
    create: false
  extraEnvVars:
    - name: ENV
      value: dev
  rbac:
    create: true
    nodeAccess: true
  existingConfigMap: fluent-bit-config