apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-logging
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
    [PARSER]
        Name    custom-tag
        Format  regex
        Regex   ^(?<namespace_name>[^_]+)\.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<container_name>.+)\.(?<container_id>[a-z0-9]{64})
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Config_Watch On
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
        Parsers_File /opt/bitnami/fluent-bit/conf/parsers.conf
        Parsers_File /opt/bitnami/fluent-bit/conf/custom_parsers.conf
    [INPUT]
        Name                tail
        Tag                 kube.<namespace_name>.<pod_name>.<container_name>.<container_id>
        Tag_Regex           (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<container_id>[a-z0-9]{64})\.log$
        Path                /var/log/containers/*
        multiline.parser    docker, cri
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.
        Regex_Parser        custom-tag
        Merge_Log           On
        Keep_Log            Off
    [FILTER]
        Name                rewrite_tag
        Match               kube.*
        Rule                $stream .* dev.kube-$TAG[1].$TAG[3] false
        Emitter_Name        re_emitted
    [OUTPUT]
        Name                forward
        Match               dev.*
        #Tag                 dev.$kubernetes['namespace_name'].$kubernetes['container_name']
        Host                dev-logproxy.hanatour.com
        Port                9880
        Compress            gzip
    [OUTPUT]
        Name                stdout
        Match               debug.*