apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-logging
  sources:
    - chart: fluent-bit
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 2.4.0
      helm:
        values: |
          daemonset:
            enabled: true
          rbac:
            create: true
            nodeAccess: true
          existingConfigMap: fluent-bit-config
    - repoURL: https://github.com/eugene70/argotest.git
      path: multi/dev/configmap
      targetRevision: main
