apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-logging
  sources:
    - chart: fluent-bit
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 2.4.0
      helm:
        valueFiles:
        - $values/multi/dev/values/values.yaml
    - repoURL: https://github.com/eugene70/argotest.git
      path: multi/dev/configmap
      targetRevision: main
    - repoURL: 'https://github.com/eugene70/argotest.git'
      targetRevision: main
      ref: values
